name: scopyon
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - scikit-image
  - jupyterlab
  - ipywidgets
  - papermill
  - plotly
  - psutil
  - click  
  - pip
  - pip:
    - git+git://github.com/ecell/scopyon.git@6671e59e18718e599ed6cedb85703bc4a43c9e60
    - mlflow>=1.0
    - kaleido
