experiment = "experiment1"

[[generation]]
  function = "user_functions.generation1"

  [generation.params]
    seed = 123
    interval = 0.033
    num_samples = 1
    # num_frames = 100
    # 5 does not guarantee the correctness of the result, but we will use 5 now...
    num_frames = 5
    exposure_time = 0.033

[template.analysis1]
  function = "user_functions.analysis1"

  [template.analysis1.params]
    max_sigma = 4
    min_sigma = 1
    threshold = 50.0
    overlap = 0.5

[[analysis]]
  template = "analysis1"
  analysis.params.threshold = 50.0

[[analysis]]
  template = "analysis1"
  analysis.params.threshold = 75.0

[[analysis]]
  template = "analysis1"
  analysis.params.threshold = 100.0

[[evaluation]]
  function = "user_functions.evaluation1"

  [evaluation.params]
    max_distance = 5.0
