experiment = "experiment1"

[[generation]]
  function = "user_functions.generation1"

  [generation.params]
    seed = 123
    interval = 0.033
    num_samples = 1
    # 5 does not guarantee the correctness of the result, but we will use 5 now...
    num_frames = 5
    # num_frames = 100
    exposure_time = 0.033
    Nm = [100, 100, 100]
    Dm = [0.222e-12, 0.032e-12, 0.008e-12]
    transmat = [
        [0.0, 0.5, 0.0],
        [0.5, 0.0, 0.2],
        [0.0, 1.0, 0.0]]

[template.analysis1]
  function = "user_functions.analysis1"

  [template.analysis1.params]
    max_sigma = 4
    min_sigma = 1
    threshold = 50.0
    overlap = 0.5

# [[analysis]]
#   [[analysis.children]]
#     template = "analysis1"

[[analysis]]
  template = "analysis1"

[[analysis]]
  template = "analysis1"
  params.threshold = 75.0

[[analysis]]
  template = "analysis1"
  params.threshold = 100.0

[[evaluation]]
  function = "user_functions.evaluation1"

  [evaluation.params]
    max_distance = 5.0
