experiment:
  name: "exp1"
  tracking_uri: "WRITEME_MLFLOW_TRACKING_URI"
  rootpath: "artifacts"
  persistent: False
  use_cache: True
  ignore_tags: False
  expand: False
  generation:
    function: "user_functions.generation1"
    params:
      seed: 123
      interval: 0.033
      num_samples: 1
      num_frames: 5
      exposure_time: 0.033
      Nm: [100, 100, 100]
      Dm: [0.222e-12, 0.032e-12, 0.008e-12]
      transmat: [
        [0.0, 0.5, 0.0],
        [0.5, 0.0, 0.2],
        [0.0, 1.0, 0.0]]
  analysis:
    function: "user_functions.analysis1"
    params:
      max_sigma: 4
      min_sigma: 1
      threshold: 50.0
      overlap: 0.5
  
